name: CI-CD

on:
 
  workflow_dispatch:
  
jobs:
 
  build_test:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
        
    steps:
      - uses: actions/checkout@v2

      - name: setup node
        uses: actions/setup-node@master
        with:
          node-version: ${{ matrix.node-version }}

      # install applicaion dependencies
      - name: Install dependencies
        run: |
          echo "npm install"
          echo "npm ci" 
      # build and test the apps     
      - name: build
        run: |
          echo "npm run build"
          echo "npm run test"
          
  push_to_Docker_Hub:
     
      runs-on: ubuntu-latest
      
      needs: [build_test]

      steps:
        - name: checkout repo
          uses: actions/checkout@v2

        - name: Set up QEMU
          uses: docker/setup-qemu-action@v1
      
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v1

        - name: Login to DockerHub
          uses: docker/login-action@v1
          with:
            username: ${{ secrets.REGISTRY_USERNAME }}
            password: ${{ secrets.REGISTRY_PASSWORD }}
      
        - name: Build and push
          uses: docker/build-push-action@v2
          with:
            context: ./
            file: ./Dockerfile
            push: true
            tags: ${{ secrets.REGISTRY_USERNAME }}/nodejs:16
          
        - name: Run the image in a container
          uses: addnab/docker-run-action@v3
          with:
            image: ${{ secrets.REGISTRY_USERNAME }}/nodejs:16
          
          
