name: Java CI With Maven

on: workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
        
        
    - name: Build with Maven
      run: echo "mvn compile"
    - name: Test with Maven
      run:  echo "mvn test"
    - name: Package with maven
      run:  echo "mvn package"
    - run: |
           cd artifact
           echo ' hi ' > sindhu.html
           cd .. 
    - uses: actions/upload-artifact@v2
      with:
       name: Package
       path: artifact  
